Fixes for python3.X
 * Fixes print statements

 * Fixes imports

 * Fixes dictionary changes for python3

 * Fixes lists and iterators especially in tests

 * Disable travis CI builds for 3.5 for now

   Am getting weird build errors such as

       ImportError: dynamic module does not define
       module export function (PyInit__openbabel)

   but it works on a fedora core 24 machine I have.

   Sigh